### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by lgarron** [commonmark/markdownhelp#16] opened 2018-05-05 02:32 UTC
https://spec.commonmark.org supports HTTPS as of https://github.com/commonmark/CommonMark-site/issues/7 ; https://commonmark.org still doesn't support it. It should be easy to turn on:

https://github.com/commonmark/CommonMark-site/issues/7#issuecomment-386441136

**Comment by macsual** [comment] 2018-05-05 07:30
https://github.com/commonmark/CommonMark-site/issues/7#issuecomment-386429516 only speaks to ["enforcing" HTTPS](https://help.github.com/articles/securing-your-github-pages-site-with-https/) which will upgrade HTTP requests to HTTPS after HTTPS is enabled.

[spec.commonmark.org](https://spec.commonmark.org) automatically began supporting HTTPS with the [announcement that custom domains on GitHub Pages have gained support for HTTPS](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/) because it is using `CNAME` records. However, [commonmark.org](https://commonmark.org) is using `A` records so [its DNS records must be updated with new IP addresses](https://help.github.com/articles/setting-up-an-apex-domain/) before it can be served over HTTPS. You can see the DNS records for each site with `dig +noall +answer <CUSTOMDOMAIN>`.

[**Configuring your domain** in the announcement](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/#configuring-your-domain) covers what I just spoke about.

**Comment by coding-horror** [comment] 2018-05-06 08:57
@jgm  if it requires DNS changes that is your department, as you control the domain name / DNS

**Comment by jgm** [comment] 2018-05-08 20:51
I've made the DNS changes, I hope correctly.
They may take a while to propagate.

**Comment by jgm** [comment] 2018-05-08 20:53
Docs say:

> Add your custom domain to your GitHub Pages site. If you're updating the IP address of an existing A record, first remove and then re-add your custom domain to the repository you’re using to publish your Pages site to trigger the process of enabling HTTPS. For more information, see "Adding or removing a custom domain for your GitHub Pages site."

**Comment by coding-horror** [comment] 2018-05-08 22:25
ok I have removed the domain and re-added it. the https option now says

> Enforce HTTPS — Not yet available for your site because the certificate has not finished being issued 
(commonmark.org) 

Hopefully that will be issued soon

**Comment by coding-horror** [comment] 2018-05-09 04:25
Hmm, 6 hours later, still stuck at

> Not yet available for your site because the certificate has not finished being issued (commonmark.org)

**Comment by coding-horror** [comment] 2018-05-09 09:33
Uh oh

> Enforce HTTPS — Unavailable for your site because your domain is not properly configured to support HTTPS (commonmark.org) 

Can you double check those DNS settings @jgm? GitHub is unhappy.

**Comment by jgm** [comment] 2018-05-09 17:03
> Can you double check those DNS settings @jgm? GitHub is unhappy.

This is what I have currently:

    % dig +noall +answer www.commonmark.org
    www.commonmark.org.	1800	IN	A	185.199.111.153
    www.commonmark.org.	1800	IN	A	185.199.109.153
    www.commonmark.org.	1800	IN	A	185.199.108.153
    www.commonmark.org.	1800	IN	A	185.199.110.153
    % dig +noall +answer commonmark.org
    commonmark.org.		1800	IN	A	185.199.110.153
    commonmark.org.		1800	IN	A	185.199.108.153
    commonmark.org.		1800	IN	A	185.199.111.153
    commonmark.org.		1800	IN	A	185.199.109.153

Thcis was what I *thought* GitHub was asking for, but I
may have misunderstood.  Can you read through the documentation linked
above and suggest changes?

**Comment by coding-horror** [comment] 2018-05-09 23:30
for an apex domain, that looks correct to me .. `commonmark.org` is an apex domain.

I removed and re-added the custom domain _again_, it currently says

>  Not yet available for your site because the certificate has not finished being issued (commonmark.org) 

again. I don't know what's happening. I wonder if it's getting mixed up because of the two entries for www and the apex domain? Do you see anything wrong here @macsual ?

**Comment by macsual** [comment] 2018-05-10 02:58
@coding-horror I wasn't aware before that there was a `www` subdomain present redirecting to the apex domain so that seems to change things slightly. Based on [these instructions](https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/), it appears that the `www` subdomain needs its DNS records modified. It needs some `CNAME` records.

The DNS records for the apex domain seem good so I think once @jgm makes the adjustments for the `www` subdomain based on [these instructions](https://help.github.com/articles/setting-up-a-www-subdomain/) then things should work once you update the `CNAME` file in the repo again.

I'd just like to point out that to enable GitHub's "HTTPS enforcement" that there is a caveat pointed out on [this page](https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/):

> Warning: If your domain has HTTPS enforcement enabled, GitHub Pages' servers will not automatically route redirects. You must configure www subdomain and root domain redirects with your domain registrar.

**Comment by jgm** [comment] 2018-05-10 03:46
I added a CNAME record for the www subdomain.
Let me know if that does the trick, @coding-horror.

**Comment by coding-horror** [comment] 2018-05-10 04:31
I removed the custom domain and added it again

>  Not yet available for your site because the certificate has not finished being issued (commonmark.org) 

Will wait a few hours and see

**Comment by coding-horror** [comment] 2018-05-10 04:47
It changed to 

>  Unavailable for your site because your domain is not properly configured to support HTTPS (commonmark.org) 

So I think we are still stuck. What else can we do @macsual ?

**Comment by macsual** [comment] 2018-05-10 05:45
Okay @coding-horror, at this point I'm not so certain because I've ran the `dig` commands over and over again and compared the results to those of [webassembly.org](https://webassembly.org/) and I just can't pinpoint the issue. I was reading [Troubleshooting custom domains](https://help.github.com/articles/troubleshooting-custom-domains/) and having exhausted so many other possibilities, I decided to investigate if the [`CNAME` has already been taken](https://help.github.com/articles/troubleshooting-custom-domains/#cname-already-taken).

I ran a search on GitHub using the query "[path:/ filename:CNAME commonmark.org](https://github.com/search?q=path%3A%2F+filename%3ACNAME+commonmark.org)" (**note:** you must be logged in) and found only one other repository besides [commonmark/web](https://github.com/commonmark/web) that has a `CNAME` file containing "commonmark.org" in it which is [nicksahler/coding-horror.github.io](https://github.com/nicksahler/coding-horror.github.io) with the file [here](https://github.com/nicksahler/coding-horror.github.io/blob/8923961e34bed8f17dbe6e15067c707ade5d74f9/CNAME).

So maybe removing the `CNAME` file in that other repo will help to resolve this issue?

**Comment by coding-horror** [comment] 2018-05-10 06:21
OK, I do know Nick, I'll ask him to delete that repo and see if that helps.
Just sent the email.

**Comment by coding-horror** [comment] 2018-05-10 20:25
ok that repo was deleted, I also removed the domain name and re-added it again. Let's see if that helps..

**Comment by coding-horror** [comment] 2018-05-10 22:29
> Not yet available for your site because the certificate has not finished being issued (commonmark.org) 

Not looking good. I'll check tomorrow but we might be stuck here and have to give up on this, I can't even think of anything else to try.. sorry @macsual

**Comment by jgm** [comment] 2018-05-11 04:43
We've got to find some way to make this work.  Not good for people to visit the site and see a scary warning about how someone might be trying to steal your information!

@coding-horror, are you sure the CNAME file should contain `commonmark.org` and not `www.commonmark.org`?  (I don't know much about this stuff, just asking.  On the spec site CNAME contains `spec.commonmark.org`, and that one works.)

**Comment by coding-horror** [comment] 2018-05-11 05:29
> Not yet available for your site because the certificate has not finished being issued (commonmark.org) 

I just don't know what could be wrong, we've checked the documentation and everything appears to be in order?

bear in mind that commonmark.org is an APEX domain so the rules are different for that. You typically redirect from www to the apex. But all the apex rules seem to be met, based on my read of the documentation?

I dunno, maybe someone from GitHub could assist.

**Comment by rishabhnambiar** [comment] 2018-07-27 04:47
@coding-horror @jgm 
The certificate took almost a week to issue in my case and I could only check the `Enforce HTTPS` option after a week.
I'll post my settings that **work** for me now, maybe comparing settings will help:
- In the CNAME record, make sure that you've included the trailing dot after github.io as shown below.
- The 4 IP addresses shown below should be used, this is not documented well but these are the latest IPs
 ### Namecheap DNS
![dns](https://user-images.githubusercontent.com/5862206/43301822-0a89ee7c-9185-11e8-80f3-a745a025c994.png)
### Make sure that you've mentioned the custom domain like this:

![pages](https://user-images.githubusercontent.com/5862206/43301292-d965dee4-9181-11e8-8e3a-78dede0e0604.png)
I'd be happy to help figure this out, let me know :+1:

**Comment by MarkTiedemann** [comment] 2018-07-27 05:49
Not quite sure what's wrong here, but [https://github.com/github/pages-health-check](https://github.com/github/pages-health-check) might help you troubleshoot.

**Comment by coding-horror** [comment] 2018-07-27 09:38
Well, I changed nothing, I just checked "enforce HTTPS" .. which had no mention of the prior problem...

> Not yet available for your site because the certificate has not finished being issued (commonmark.org)

and now it .. magically seems good? https://commonmark.org/ 🕶

**Comment by bitcoinctf** [comment] 2018-07-28 11:20
There is still an invalid certificate for the www domain though: https://www.commonmark.org/

**Comment by macsual** [comment] 2018-07-29 02:33
@coding-horror can #17 be merged now?

**Comment by jgm** [comment] 2018-07-30 17:31
Reopening because of the invalid certification for www.commonmark.org.
Anyone know what we need to do to fix this?

**Comment by coding-horror** [comment] 2018-07-30 20:39
You'll need to use DNS controls to redirect www to the apex domain.

**Comment by bitcoinctf** [comment] 2018-12-03 03:33
It looks like if you just use an A record for both, no CNAME, you get the expected behaviour. You can see an example here: https://davidojeda.mx/ + https://github.com/davidojedalopez/davidojedalopez.github.io/blob/master/CNAME

Note that there is no certificate error when visiting https://www.davidojeda.mx/

**Comment by coding-horror** [comment] 2019-04-09 03:16
this is all good now thanks!

**Closed as completed by coding-horror** 2019-04-09 03:16 UTC
